name: 📊 Generar reporte con Quarto

on:
  workflow_run:
    workflows: ["🔄 Actualizar base de datos desde QFieldCloud ☁︎"]
    types:
      - completed

permissions:
  contents: write 

jobs:
  render-report:
    runs-on: macos-latest 

    steps:
      - name: Clonar repositorio 📥
        uses: actions/checkout@v3

      - name: Instalar R y dependencias 🧪
        uses: r-lib/actions/setup-r@v2

      - name: Instalar Quarto 📦
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Instalar paquetes R necesarios 📚
        run: |
          Rscript -e 'install.packages(c("sf", "janitor", "pak","dplyr","DT"))'
          Rscript -e 'pak::pkg_install("walkerke/mapgl")'

      - name: Mostrar archivos
        run: ls -R
   
      - name: Renderizar reporte con Quarto 📄
        run: |
         quarto render reporte/report.qmd --output-dir docs

      - name: Commit del reporte generado 📝
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "📊 Render Quarto report - $TIMESTAMP" || echo "Sin cambios"
          git push origin main
